/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,jsx}",
    "./components/**/*.{js,jsx}",
    "./app/**/*.{js,jsx}",
    "./features/**/*.{js,jsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-variant": "var(--color-surface-variant, #e5e2e1)",
        "tertiary-fixed": "var(--color-tertiary-fixed, #6bfe9c)",
        "on-error-container": "var(--color-on-error-container, #93000a)",
        "inverse-surface": "var(--color-inverse-surface, #303030)",
        "on-secondary": "var(--color-on-secondary, #ffffff)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant, #454747)",
        "secondary-container": "var(--color-secondary-container, #dfe0e0)",
        "error": "var(--color-error, #ba1a1a)",
        "inverse-primary": "var(--color-inverse-primary, #ffb59d)",
        "on-surface-variant": "var(--color-on-surface-variant, #594139)",
        "tertiary-container": "var(--color-tertiary-container, #00b15c)",
        "on-error": "var(--color-on-error, #ffffff)",
        "on-tertiary": "var(--color-on-tertiary, #ffffff)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim, #c6c6c7)",
        "surface-tint": "var(--color-surface-tint, #ab3500)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed, #1a1c1c)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed, #00210c)",
        "surface-container-highest": "var(--color-surface-container-highest, #e5e2e1)",
        "on-primary-container": "var(--color-on-primary-container, #5f1900)",
        "background": "var(--color-background, #fcf9f8)",
        "surface-dim": "var(--color-surface-dim, #dcd9d9)",
        "on-primary-fixed": "var(--color-on-primary-fixed, #390c00)",
        "primary": "var(--color-primary, #ab3500)",
        "primary-container": "var(--color-primary-container, #ff6b35)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant, #832600)",
        "on-background": "var(--color-on-background, #1b1b1c)",
        "on-primary": "var(--color-on-primary, #ffffff)",
        "tertiary": "var(--color-tertiary, #006d37)",
        "surface-container": "var(--color-surface-container, #f0eded)",
        "primary-fixed": "var(--color-primary-fixed, #ffdbd0)",
        "on-secondary-container": "var(--color-on-secondary-container, #616363)",
        "secondary-fixed": "var(--color-secondary-fixed, #e2e2e2)",
        "surface-container-high": "var(--color-surface-container-high, #eae7e7)",
        "on-surface": "var(--color-on-surface, #1b1b1c)",
        "surface-bright": "var(--color-surface-bright, #fcf9f8)",
        "error-container": "var(--color-error-container, #ffdad6)",
        "surface-container-low": "var(--color-surface-container-low, #f6f3f2)",
        "on-tertiary-container": "var(--color-on-tertiary-container, #003b1a)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim, #4ae183)",
        "outline-variant": "var(--color-outline-variant, #e1bfb5)",
        "inverse-on-surface": "var(--color-inverse-on-surface, #f3f0ef)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim, #ffb59d)",
        "surface": "var(--color-surface, #fcf9f8)",
        "outline": "var(--color-outline, #8d7168)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant, #005228)",
        "surface-container-lowest": "var(--color-surface-container-lowest, #ffffff)",
        "secondary": "var(--color-secondary, #5d5f5f)"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px"
      },
      spacing: {
        xl: "48px",
        "margin-mobile": "20px",
        "margin-desktop": "64px",
        md: "24px",
        xs: "8px",
        gutter: "16px",
        base: "4px",
        lg: "32px",
        sm: "16px"
      },
      fontFamily: {
        "display-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        reveal: {
          from: { opacity: '0', transform: 'scale(0.95) translateY(20px)' },
          to: { opacity: '1', transform: 'scale(1) translateY(0)' },
        },
        'subtle-zoom': {
          from: { transform: 'scale(1)' },
          to: { transform: 'scale(1.1)' },
        },
        shine: {
          '0%': { left: '-100%' },
          '50%': { left: '100%' },
          '100%': { left: '100%' },
        },
        fadeInUp: {
          from: { opacity: '0', transform: 'translateY(20px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        floating: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-15px)' },
        }
      },
      animation: {
        float: 'float 6s ease-in-out infinite',
        reveal: 'reveal 1.2s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'subtle-zoom': 'subtle-zoom 20s linear infinite alternate',
        shine: 'shine 4s infinite',
        fadeInUp: 'fadeInUp 0.8s cubic-bezier(0.16, 1, 0.3, 1) both',
        floating: 'floating 6s ease-in-out infinite',
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
}
